# Generated by Django 6.0.1 on 2026-02-03 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='archivo',
            field=models.ImageField(blank=True, null=True, upload_to='tickets/', verbose_name='Captura de Pantalla'),
        ),
    ]
