# Generated by Django 6.0.1 on 2026-02-05 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_articulo_alter_ticket_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='perfiles/'),
        ),
    ]
