# Generated by Django 6.0.1 on 2026-02-05 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_etiqueta_ticket_etiquetas_historialticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Proyecto')),
                ('progreso', models.IntegerField(default=0, verbose_name='% Progreso')),
                ('estado_texto', models.CharField(max_length=200, verbose_name='Estado Actual (Ej: Falta módulo X)')),
                ('tiempo_estimado', models.CharField(blank=True, max_length=100, verbose_name='Tiempo Restante (Ej: 2 semanas)')),
                ('visible', models.BooleanField(default=True, verbose_name='Visible para usuarios')),
            ],
        ),
    ]
