# Generated by Django 6.0.1 on 2026-02-23 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_proyecto'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='categoria',
            field=models.CharField(choices=[('SOFTWARE', '💻 Software / Aplicaciones'), ('HARDWARE', '🔌 Hardware / Equipos'), ('REDES', '🌐 Redes e Internet'), ('ACCESOS', '🔐 Accesos y Contraseñas'), ('OTROS', '📁 Otros')], default='SOFTWARE', max_length=20, verbose_name='Categoría'),
        ),
    ]
